# Site settings
title: Black Ridge Contractors
email: traviscottam@gmail.com
description: Southern Utah's Greatest Excavators
baseurl: '/brc' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Saint George
state: Utah
zip_code: 84765
country: United States of America
phone: (801) 318-7903

icon: fa-connectdevelop # Font Awesome class for your site's icon

# Social settings
facebook_url: \#
github_url: \#
gitlab_url: \#
googleplus_url: \#
instagram_url: \#
linkedin_url: \#
pinterest_url: \#
slack_url: \#
twitter_url: \#

# Build settings
markdown: kramdown

sass:
  style: compressed
