# Site settings
title: Black Ridge Contractors
email: traviscottam@gmail.com
description: Southern Utah's Greatest Excavators
baseurl: '/brc2' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Saint George
state: Utah
zip_code: 84765
country: United States of America
phone: (801) 318-7903

icon: fa-connectdevelop # Font Awesome class for your site's icon

# Social settings
facebook_url: https://buchanankerswell.com/brc
github_url: https://buchanankerswell.com/brc
gitlab_url: https://buchanankerswell.com/brc
googleplus_url: https://buchanankerswell.com/brc
instagram_url: https://buchanankerswell.com/brc
linkedin_url: https://buchanankerswell.com/brc
pinterest_url: https://buchanankerswell.com/brc
slack_url: https://buchanankerswell.com/brc
twitter_url: https://buchanankerswell.com/brc

# Build settings
markdown: kramdown

sass:
  style: compressed
